# -*- coding: utf-8 -*-
{
    'name': "Report Picking Type",

    'summary': """
        Menampilkan Beragam Informasi Berdasarkan Referensi Picking Yang Akan Diprint""",

    'description': """
PICKING REPORT TYPE STBJ STBN
=============================
1. Bila Picking Reference STBJ Maka Tampilkan Tabel Tanda Tangan, Generated Date, Generated By,
2. Bila Picking Reference STBN Maka Tampilkan Tabel Berat Kain, Lebar Kain, Total Roll, Keterangan
3. Bila Picking Reference SJPB Maka Tampilkan Tabel Keterangan
4. Tambahkan No Barcode Pada Gambar Barcode
    """,

    'author': "odoo-consultants",
    'website': "http://www.odoo-consultants.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/module/module_data.xml
    # for the full list
    'category': 'Report',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['po_picking_multi_sequence'],

    # always loaded
    'data': [
        'views/picking_report_type_templates.xml',
        'views/purchase_order_views.xml',
    ],
}
